### ISSUE TITLE
Write out list of queries needed for interaction with CLI and frontend

### ISSUE THREAD

**Issue by acashmoney** [labdao/openlab-exchange-subgraph#2]
API endpoint calls needed for job submission, completion, etc.

**Comment by acashmoney** [comment]
@NiklasTR to write some use cases for when we need certain pieces of information (example: we need to fetch all jobs with status OPEN so providers can see a list of all jobs they can accept)

**Comment by blahah** [comment]
We have the current queries as reference:
https://github.com/labdao/openlab-cli/blob/21c88b72eab87539630b819f37ec4f9342859302/src/lib/exchange/graph.ts

I am closing this issue as we have the current implementation as a functional spec. We can open new issues if we need to document new requirements.
