### ISSUE TITLE
Subgraph truncating decimals when user inputs decimal job cost

### ISSUE THREAD

**Issue by acashmoney** [labdao/openlab-exchange-subgraph#4]
[Transaction](https://mumbai.polygonscan.com/tx/0xa05a4134338b4bfa09a9eb1a5ab6a133c000e305ee4164ba7d2d39f831d39e56)

Subgraph query output
```
      {
        "client": "0x6d0083db5e90a6fa03970f98523262e7fe044ddc",
        "id": "0xd",
        "jobCost": "0",
        "jobURI": "bafkreiasb4553aycgtwlkgomogk75pc46ndrf47zhrauzszj42ajx7ovui",
        "openlabNFTURI": null,
        "payableToken": "0x7fd2493c6ec0400be7247d6a251f00fdccc17375",
        "provider": null,
        "status": 0
      }
```

jobCost should not be displaying 0

**Comment by blahah** [comment]
@acashmoney what's the status on this? Let's document the investigation if there's been one so far, or add it to a milestone if it still needs attention.

**Comment by acashmoney** [comment]
@blahah issue was related to typing of the job costs. See commit 5b277e62db40a95efc87b78e964fd7e8cb703d86
